---
- name: Install i3
  pacman:
    name:
      - i3-gaps
      - i3blocks
      - i3lock
      - i3status
    state: present

- name: Install arandr
  pacman:
    name:
      - arandr
    state: present

- name: Install lxappearance
  pacman:
    name:
      - lxappearance
    state: present

- name: Install thunar
  pacman:
    name:
      - thunar
    state: present

- name: Install rofi 
  pacman:
    name:
      - rofi 
    state: present

- name: Install compton 
  pacman:
    name:
      - compton 
    state: present

- name: Install terminator
  pacman:
    name:
      - terminator
    state: present

- name: Install firefox-developer-edition
  pacman:
    name:
      - firefox-developer-edition
    state: present

- name: Install dunst 
  pacman:
    name:
      - dunst 

- name: Install flatpak 
  pacman:
    name:
      - flatpak 

- name: Create the rofi folder 
  file:
    path: $HOME/gui/rofi 
    state: directory
    mode: '0755'
  become_user: johrun

- name: Create the rofi theme folder 
  file:
    path: $HOME/gui/rofi/themes
    state: directory
    mode: '0755'
  become_user: johrun

- name: Copy rofi theme
  copy: src=rofi-nord.rasi dest=$HOME/gui/rofi/themes/rofi-nord.rasi
  become_user: johrun
