---
- name: Install base-devel
  pacman:
    name:
      - base-devel
    state: present

- name: Install cmake 
  pacman:
    name:
      - cmake 
    state: present

- name: Install zsh
  pacman:
    name:
      - zsh
    state: present

